const Map<String, String> ko = {
  "appName": "우리사이",
  "splashText1": "너와 나의 가장 쉬운 소통",
  "bottoms1Title": "우리사이",
  "bottoms2Title": "친구",
  "bottoms3Title": "인맥",
  "bottoms4Title": "더보기",
  "appBar1Title": "우리사이",
  "appBar2Title": "친구",
  "appBar3Title": "인맥",
  "appBar4Title": "더보기",
  "appBar1ShareTooltip": "우리사이 어플을 공유",
  "appBar1Share1": "SMS 공유",
  "appBar1Share2": "소셜 공유",
  "appBar1Share3": "QR코드 공유",
  "shareMessage": "너와 나의 가장 쉬운 소통 ''우리사이'' 앱 공유",
  "shareQrMessage": "QR 코드를 스캔하여 \n''우리사이'' 앱을 설치 하세요.",
  "youAndIBottomLeftTitle": "공유 범위 설정",
  "youAndIBottomRightTitle": "가이드",
  "youAndIBottomRightTitleFile": "파일공유",
  "youAndIBottomChip1": "전화번호 전달",
  "youAndIBottomChip2": "추가정보 전달" ,
  "youAndIBottomChip3": "인맥정보 매칭",
  "youAndIBottomChipContent1_1": "전화번호 전달 범위 설정(친구탭에만 해당)",
  "youAndIBottomChipContent1_2": "휴대폰 번호와 전화를 공유할지 설정 합니다.",
  "youAndIBottomChipContent2_1": "기타 전달 범위 설정(친구탭에만 해당)",
  "youAndIBottomChipContent2_2": "직급, 이메일, 주소를 공유할지 설정합니다.",
  "youAndIBottomChipContent3_1": "인맥정보 매칭 설정(인맥탭에만 해당)",
  "youAndIBottomChipContent3_2": "같은 인맥을 찾아줄지 설정합니다.",
  "youAndIBottomTab1": "정보 공유",
  "youAndIBottomTab2": "데이터 공유",
  "youAndIProfile1": "* 이름",
  "youAndIProfile2": "직급",
  "youAndIProfile3": "* 휴대폰",
  "youAndIProfile4": "전화",
  "youAndIProfile5": "이메일",
  "youAndIProfile6": "주소",
  "youAndIProfile7": "메모",
  "youAndIProfileSave": "저장",
  "friendTitle": "친구(@length명)",
  "friendSearchText": "친구를 검색하세요.",
  "friendNoListText": "서로 부딪쳐 친구를 만들어 보세요.",
  "youAndIMessage1_1": "준비 중...",
  "youAndIMessage1_2": "잠시만 기다려 주세요.",
  "youAndIMessage2_1": "연결 가능!",
  "youAndIMessage2_2": "기기를 서로 부딪쳐 연결해 주세요.",
  "youAndIMessage3_1": "찾는 중...",
  "youAndIMessage3_2": "친구의 기기를 찾는 중입니다.",
  "youAndIMessage31_1": "친구를 찾지 못했어요.",
  "youAndIMessage31_2": "★ 각도를 맞추어 동시에 시도해주세요.",
  "youAndIMessage4_1": "연결 확인!",
  "youAndIMessage4_2": "서로의 정보가 맞는지 확인해주세요.",
  "youAndIMessage5_1": "연결 되었습니다.",
  "youAndIMessage5_2": "이제 서로의 정보가 공유되었습니다.",
  "youAndIMessage0_1": "연결 실패!",
  "youAndIMessage0_2": "인터넷 연결 상태를 확인해주세요.",
  "youAndIMessage6_1": "친구를 찾았어요!",
  "youAndIMessage6_2": "정보를 공유해 보세요.",
  "dataConfirmTitle": "정보 교환",
  "dataConfirmContent": "@name(@phone)님과 정보를 교환하시겠습니까?",
  "dataConfirmCancel": "아니오",
  "dataConfirmOK": "네",
  "sendprofileDialog": "프로필을 전송 중 입니다.",
  "networkSearchText": "인맥을 검색하세요.",
  "networkNoListText": "서로 부딪쳐 인맥를 찾아 보세요.",
  "networkTitle": "인맥(@length명)",
  "networkListName": "@name의 인맥 @length명",
  "networkDetailTitle": "나와 @name의 인맥 @length명",
  "networkDetailButton1": "정보",
  "networkDetailButton2": "인맥 관계도(@length명)",
  "networkDetailDiagramTitle": "@name의 인맥 관계도(@length명)",
  "bottomDataPathMessage": "저장 경로\n@path",
  "fileShareMessage": "공유하실 파일을 선택하시겠습니까?",
  "fileShareMessageOK": "공유파일 선택",
  "fileShareMessageCANCEL": "파일 수신만하기",
  "p2pconnectMsg": "P2P 접속 중 입니다.\n동일 네트워크가 아니면 약간의 접속 시간이 소요될 수 있습니다.",
  "p2pDataSendMsg": "P2P로 데이터 전송 중 입니다.",
  "notice": "알림",
  "p2pDataComplete": "데이터 전송이 완료되었습니다.",
  "p2pDataReceiveComplete": "데이터 수신이 완료되었습니다.\n파일 탐색기를 통해 파일을 확인할 수 있습니다.",
  "tutorialMessage1_1": "우리가 만나",
  "tutorialMessage1_2": "가장 쉬운 소통 방법.",
  "tutorialMessage2_1": "이젠 부딪치기만 하세요.",
  "tutorialMessage2_2": "원하는 정보만 교환할 수 있습니다.",
  "tutorialMessage3_1": "서로의 인맥을 찾아줘요.",
  "tutorialMessage3_2": "상상하지도 못 할 일이 벌어질꺼예요~",
  "tutorialMessage4_1": "서로 파일을 주고 받으세요.",
  "tutorialMessage4_2": "놀랍게도 한번 부딪치면 끝입니다.",
  "tutorialMessage5_1": "개인간 교환방식으로 원천 차단.",
  "tutorialMessage5_2": "소중한 개인 정보를 지켜드립니다.",
  "tutorialMessage5_3": "모든 개인 정보는 서버에 저장하지 않아요~",
  "moreIcon1": "공지사항",
  "moreIcon2": "자주하는 질문",
  "moreIcon3": "1:1 문의",
  "moreIcon4": "연락처 숨김",
  "moreIcon5": "설정",
  "vaildCheck1": "필수 정보 부족!",
  "vaildCheck2": "이름을 입력해주세요.",
  "vaildCheck3": "핸드폰 번호를 입력해주세요.",
  "moreHideContectTitle": "연락처 숨김",
  "moreHideContectSearchText": "이름으로 검색하세요.",
  "moreHideContectNoListText": "연락처 없습니다.",
  "moreHideContectHideText": "숨김",
  "addressSearch": "주소검색",
  "addressSearchTitle": "위치 선택",
  "addressSelect": "선택",
  "wait": "잠시만 기다려주세요.",
  "youAndIProfile61": "상세주소",
};
